server:
  port: 8080
  servlet:
    context-path: /

#mybatis 配置
mybatis:
  type-aliases-package: com.example.demo.entity
  mapper-locations: classpath:mybatis/mapper/**/*.xml
#  配置效果同config-location
#  configuration:
#    default-statement-timeout: ${mybatis.defaultStatementTimeout}
#    default-executor-type: simple
  config-location: classpath:mybatis/mybatis-config.xml

#spring配置
spring:
  datasource:
    url: ${datasource.url}
    username: ${datasource.username}
    password: ${datasource.password}
    driver-class-name: com.mysql.cj.jdbc.Driver
    # Druid 数据源配置，继承spring.datasource.* 配置，相同则覆盖
    druid:
      initial-size: 5
      max-active: 5
      min-idle: 5
      filter:
        stat:
          enabled: true
          db-type: mysql
          log-slow-sql: true
          slow-sql-millis: 2000
      # Druid 数据源 1 配置，继承spring.datasource.druid.* 配置，相同则覆盖
      one:
        initial-size: 1
        max-active: 1
      # Druid 数据源 2 配置，继承spring.datasource.druid.* 配置，相同则覆盖
      two:
        initial-size: 2
        max-active: 2
  redis:
#    host: ${redis.host}
#    port: ${redis.port}
#    password: ${redis.password}
    lettuce:
      pool:
        min-idle: 2
    cluster:
      nodes: 192.168.3.138:7000,192.168.3.138:7001,192.168.3.138:7002,192.168.3.138:7003,192.168.3.138:7004,192.168.3.138:7005

#log 日志配置
logging:
  level:
    root: ${log.level}
    com:
      shimao:
        iot:
          udp: info
      example:
        demo: ${log.com.example.demo.level}

redis:
  serverType: ${redis.serverType}

udp:
  group-map:
    group-1: 224.1.1.1:9000
    group-2: 224.1.1.2:9000
    group-3: 127.0.0.1:9000
  multicast-groups:
    - group-1
    - group-2
    - group-4
  max-rcv-buf-allocator: 2048
  port: 9000
  max-wait-times: 5
  secret: true
  secret-key: 892f0b160826fdf2ec083d55e91db457
  sign: true
