#公共配置与profiles选择无关
mybatis:
  typeAliasesPackage: com.example.demo.entity
  mapperLocations: classpath:mybatis/mapper/**/*.xml
  configLocation: classpath:mybatis/mybatis-config.xml

#开发配置
spring:
  datasource:
#    url: ${datasource.url}
#    username: ${datasource.username}
#    password: ${datasource.password}
    url: jdbc:mysql://192.168.5.181:3306/hellodemo
    username: root
    password: Yunzhisheng!123
    driver-class-name: com.mysql.cj.jdbc.Driver
    # Druid 数据源配置，继承spring.datasource.* 配置，相同则覆盖
    druid:
      initial-size: 5
      max-active: 5
      filter:
        stat:
          enabled: true
          db-type: mysql
          log-slow-sql: true
          slow-sql-millis: 2000
      # Druid 数据源 1 配置，继承spring.datasource.druid.* 配置，相同则覆盖
      one:
        initial-size: 1
        max-active: 1
      # Druid 数据源 2 配置，继承spring.datasource.druid.* 配置，相同则覆盖
      two:
        initial-size: 2
        max-active: 2

