server:
  port: 8080
  servlet:
    context-path: /

#mybatis 配置
mybatis:
  type-aliases-package: com.example.demo.entity
  mapper-locations: classpath:mybatis/mapper/**/*.xml
#  配置效果同config-location
#  configuration:
#    default-statement-timeout: ${mybatis.defaultStatementTimeout}
#    default-executor-type: simple
  config-location: classpath:mybatis/mybatis-config.xml

#spring配置
spring:
  datasource:
    url: ${datasource.url}
    username: ${datasource.username}
    password: ${datasource.password}
    driver-class-name: com.mysql.cj.jdbc.Driver
    # Druid 数据源配置，继承spring.datasource.* 配置，相同则覆盖
    druid:
      initial-size: 5
      max-active: 5
      min-idle: 5
      filter:
        stat:
          enabled: true
          db-type: mysql
          log-slow-sql: true
          slow-sql-millis: 2000
      # Druid 数据源 1 配置，继承spring.datasource.druid.* 配置，相同则覆盖
      one:
        initial-size: 1
        max-active: 1
      # Druid 数据源 2 配置，继承spring.datasource.druid.* 配置，相同则覆盖
      two:
        initial-size: 2
        max-active: 2

#log 日志配置
logging:
  level:
    root: ${log.level}
    com:
      example:
        demo: ${log.com.example.demo.level}

